- hosts: all
  gather_facts: no 
  tasks:
     
   - name:  init asm
     become: true
     become_user: root
     become_method: pbrun
     command: /usr/sbin/oracleasm init

   - name: create DATADG ASM Disk(s)
     become: true
     become_user: root
     become_method: pbrun
     command: /usr/sbin/oracleasm createdisk DATADG /dev/xvdf1
 
   - name: create FLASHDG ASM Disk(s)
     become: true
     become_user: root
     become_method: pbrun
     command: /usr/sbin/oracleasm createdisk FLASHDG /dev/xvdh1
     
   - name: create ASMDG ASM Disk(s)
     become: true
     become_user: root
     become_method: pbrun
     command: /usr/sbin/oracleasm createdisk ASMDG /dev/xvdi1 

   - name: Change ownership of /dev/xvdf1 file system
     become: true
     become_user: root
     become_method: pbrun
     file:
        path: /dev/xvdf1
        owner: oracle
        group: oinstall
        mode: 0600

   - name: Change ownership of /dev/xvdh1 file system
     become: true
     become_user: root
     become_method: pbrun
     file:
        path: /dev/xvdh1
        owner: oracle
        group: oinstall
        mode: 0600
        
   - name: Change ownership of /dev/xvdi1 file system
     become: true
     become_user: root
     become_method: pbrun
     file:
        path: /dev/xvdi1
        owner: oracle
        group: oinstall
        mode: 0600    

   - name: Passwd delete oracle
     become: true
     become_user: root
     become_method: pbrun
     command: passwd --delete oracle
   
   - name: Permission Change in /swbackup
     become: true
     become_user: root
     become_method: pbrun
     shell: chown oracle:oinstall -R /swbackup; chmod 777 -R /swbackup 


   - name: create directory /apps/opt/oraInventory
     become: true
     become_user: root
     become_method: pbrun
     file:
       path: /apps/opt/oraInventory
       state: directory
       owner: oracle
       group: oinstall
       mode: 0777
       
   - name: copy utilities to /apps/opt/oracle
     shell: cp /swbackup/utilities.tar.gz /apps/opt/oracle
     become: true
     become_user: oracle
     become_method: su
     
   - name: untar  utilities
     shell: cd /apps/opt/oracle; tar -xvf utilities.tar.gz
     become: true
     become_user: oracle
     become_method: su 

   - name: copy grid_home to /apps/opt/grid/product/12.2.0
     shell: cp /swbackup/linuxx64_12201_grid_home.zip /apps/opt/grid/product/12.2.0
     become: true
     become_user: oracle
     become_method: su     
      
   - name: unzip linuxx64_12201_grid_home.zip
     shell: cd /apps/opt/grid/product/12.2.0; unzip -o linuxx64_12201_grid_home.zip
     become: true
     become_user: oracle
     become_method: su
    
   - name: unzip linuxx64_12201_database.zip
     shell: cd /swbackup; unzip -o linuxx64_12201_database.zip
     become: true
     become_user: oracle
     become_method: su 
   - name: unzip linuxx64_12201_database.zip
     shell: cd /swbackup; unzip -o p26247490_12201170823ACFSRU_Linux-x86-64.zip
     become: true
     become_user: oracle
     become_method: su  
     
     
   - name: install asm binaries
     become: true
     become_user: oracle
     become_method: su
     shell: /apps/opt/grid/product/12.2.0/gridSetup.sh -silent -skipPrereqs -responseFile /swbackup/gridsetup.rsp > /swbackup/install_grid.txt
     
   - name: Create Wallet
     become: true
     become_user: oracle
     become_method: su
     shell: echo "oracle123" >> std.txt; export host=`hostname | tr -d '.ebiz.verizon.com'`; /apps/opt/grid/product/12.2.0/OPatch/auto/core/bin/patchingWallet.sh -walletDir /apps/opt/grid/wallet -create oracle:$host:ssh  -useStdin < /swbackup/std.txt -log /apps/opt/grid/wallet/wallet.log -force > /swbackup/wallet.txt 
     
   - name: install Patch 26751067
     become: true
     become_user: root
     become_method: pbrun
     shell: /apps/opt/grid/product/12.2.0/OPatch/opatchauto apply /swbackup/12.2.0/PATCH/26751067 -oh /apps/opt/grid/product/12.2.0 -wallet /apps/opt/grid/wallet > /swbackup/install_26751067_patch.txt  

     
   - name: install Patch 26247490
     become: true
     become_user: root
     become_method: pbrun
     shell: /apps/opt/grid/product/12.2.0/OPatch/opatchauto apply /swbackup/26247490 -oh /apps/opt/grid/product/12.2.0 -wallet /apps/opt/grid/wallet > /swbackup/install_26247490_patch.txt

     
   - name: Run orainstRoot.sh
     become: true
     become_user: root
     become_method: pbrun
     shell: /apps/opt/oraInventory/orainstRoot.sh >> /swbackup/orainstRoot.log
     
   - name: Run root.sh
     become: true
     become_user: root
     become_method: pbrun
     shell: /apps/opt/grid/product/12.2.0/root.sh > /swbackup/Root.log

   - name: create ASM instance
     become: true
     become_user: oracle
     become_method: su
     command: /apps/opt/grid/product/12.2.0/bin/asmca -silent  -configureASM  -diskString '/dev/xvd*1' -sysAsmPassword oracle123 -asmsnmpPassword oracle123 -diskGroupName ASMDG -diskList '/dev/xvdi1' -redundancy EXTERNAL 
    
   - name: create disk group DATADG
     become: true
     become_user: oracle
     become_method: su
     command: /apps/opt/grid/product/12.2.0/bin/asmca -silent -createDiskGroup  -diskString '/dev/xvd*1' -diskGroupName DATADG -diskList '/dev/xvdf1' -redundancy EXTERNAL
     
   - name: create disk group FLASHDG
     become: true
     become_user: oracle
     become_method: su
     command: /apps/opt/grid/product/12.2.0/bin/asmca -silent -createDiskGroup  -diskString '/dev/xvd*1' -diskGroupName FLASHDG -diskList '/dev/xvdh1' -redundancy EXTERNAL


   - name: install oracle binaries
     become: true
     become_user: oracle
     become_method: su
     shell: /swbackup/database/runInstaller -silent -noconfig -ignorePrereq -ignoreSysPrereqs -showProgress -waitforcompletion -responseFile /swbackup/db12_2.rsp > /swbackup/install_oracle.txt

   - name: Run root.sh
     become: true
     become_user: root
     become_method: pbrun
     shell:  /apps/opt/oracle/product/12.2.0/db_1/root.sh > /swbackup/db_Root.log
